
var myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNzUwMDIwMDE4MiIsInJvbGVfbGlzdCI6WyIxMDAiLCIxMDEiLCIxMDEwMCIsIjEwMjAwIiwiMTAzMDAiLCIxMDUwMCIsIjEwNjAwIiwiMTA5MDAiLCIxMTAwMCIsIjExMTAwIiwiMTEyMDAiLCIxMTMwMCIsIjEzODAwIiwiMTQwMDAiLCIxNDEwMCIsIjE0MjAwIiwiMTUwMDAiLCIxNjAwIiwiMTYwMDAiLCIxNzAwMCIsIjE4MDAiLCIxOTAwIiwiMTkwMDAiLCIyMDAiLCIyMjAwIiwiMjQwMCIsIjI4MDAiLCIzMDAwIiwiMzIwMCIsIjM3MDAiLCIzOTAwIiwiNDAwIiwiNTAwIiwiNTIwMCIsIjUzMDAiLCI1NDAwIiwiNTUwMCIsIjYwMCIsIjY2MDAiLCI3MDAwIiwiNzEwMCIsIjc0MDAiLCI3NTAwIiwiNzkwMCIsIjc5MDEiLCI3OTA0IiwiNzkxMCIsIjc5MTEiLCI3OTEzIiwiODAwIiwiODIwMCIsIjg3MDAiLCI4ODAwIiwiOTMwMCIsIjk0MDAiLCI5NDAxIiwiOTYwMCIsIjk3MDAiXSwidXNlcl90eXBlIjozLCJla29fdXNlcl9pZCI6MTk5MTU2LCJlbWFpbCI6InJhaHVsZ2FyZ0A5MXNvY2lhbC5jb20iLCJjb2RlIjoiOTkwMTMwOTMxIiwiem9ob19pZCI6IiIsImlhdCI6MTYzODg3NDk3MywiZXhwIjoxNjM4ODkyOTczLCJhdWQiOiI3NTAwMjAwMTgyIiwiaXNzIjoiY29ubmVjdC5la28ifQ.v75MuBjml1-39B8l6t8nQs2F9FLuj4NkAc_mRO3w7cs");

myHeaders.append("Content-Type", "application/x-www-form-urlencoded");
var urlencoded = new URLSearchParams();
urlencoded.append("user_id", "8826175074");
urlencoded.append("locale", "en");


export var requestOptions = {
method: 'POST',
headers: myHeaders,
body: urlencoded,
redirect: 'follow'
};